export enum ChangeDirectionActions {
  CHANGE_DIRECTION_TOP = 'TOP',
  CHANGE_DIRECTION_BOTTOM = 'BOTTOM',
  CHANGE_DIRECTION_LEFT = 'LEFT',
  CHANGE_DIRECTION_RIGHT = 'RIGHT',
}

export enum ChangeNumberCellsActions {
  CHANGE_NUMBER_ROWS = 'ROWS',
  CHANGE_NUMBER_COLUMNS = 'COLUMNS',
}

export enum SetDirectionActions {
  SET_DIRECTION_TOP = 'SET_TOP',
  SET_DIRECTION_BOTTOM = 'SET_BOTTOM',
  SET_DIRECTION_LEFT = 'SET_LEFT',
  SET_DIRECTION_RIGHT = 'SET_RIGHT',
}
